version: '3'
services:
  mysql:
    # platform: linux/amd64
    restart: always
    image: mysql:5.7.34
    container_name: mysql-im
    volumes:
    #   - /apps/mysql/mydir:/mydir
    #   - /apps/mysql/datadir:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf
    #   # 数据库还原目录 可将需要还原的sql文件放在这里
    #   - /apps/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=public"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
  reids:
    # platform: linux/amd64
    image: redis:7.0.4
    container_name: redis-im
    restart: always
    privileged: true
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    # command: redis-server /etc/redis/redis.conf
    ports:
      - 16379:6379
    environment:
      - REDIS_PASSWORD=1234
  mongo:
    image: mongo
    container_name: mongodb_im
    ports:
      - '27017:27017'
    command: [
      --auth
    ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: cnode
      MONGO_USERNAME: cnode
      MONGO_PASSWORD: cnode
    volumes:
        - ./docker/mongodb/.docker/mongo_data:/data/db
        - ./docker/mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh


    # env_file:
    #   - .env.development.local
